# Generated by Django 6.0.6 on 2026-06-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_poste',
            new_name='date_posted',
        ),
    ]
